### ISSUE TITLE
Team Integration 0 - Environment Setup

### ISSUE THREAD

**Issue by gucoo** [rmhowe425/NASA-SUITS-2021#1]
**Two options:**

1. Use the 2020 original repo and test on the Hololens 2
2. Building from the zero

**Reference**

https://docs.microsoft.com/en-us/windows/mixed-reality/develop/unity/tutorials/mr-learning-base-01
https://docs.microsoft.com/en-us/windows/mixed-reality/develop/unity/tutorials/mr-learning-base-02
https://docs.microsoft.com/en-us/windows/mixed-reality/develop/unity/tutorials/mr-learning-base-03
https://docs.microsoft.com/en-us/windows/mixed-reality/develop/unity/tutorials/mr-learning-base-04

**Current version**
Unity Hub, Unity 2019.4.18f1(LTS): With the Universal Windows Platform Build Support module selected https://store.unity.com/download-nuo
Visual Studio 2019 Community (You can install this through Unity Hub)
Windows 10 SDK 10.0.18362.0 or later: https://developer.microsoft.com/en-us/windows/downloads/windows-10-sdk/
Hololens2 Emulator: https://docs.microsoft.com/en-US/windows/mixed-reality/develop/install-the-tools?tabs=unity

**Comment by kmenke1** [comment]
1/24/21: All Developers
Guan-Wen/ Richard: Option 1 is not viable because we have obsolete packages and HoloLens 2 has too many new functions. We have compilation errors

Therefore, everyone need follow option 2 by following Reference links below option2

**Comment by gucoo** [comment]
Next step: Create a button using MRTK and activate a panel as before
